### ISSUE TITLE
MapboxAccessToken is invalid pk 

### ISSUE THREAD

**Issue by nozhant** [crazycapivara/docker-kepler.gl#9]
I tried run this image with **MapboxAccessToken** variable but it's not valid I also tried with **mapboxApiAccessToken**
and it's not valid either

```
MapboxAccessToken=[My mapbox token]
^

ReferenceError: pk is not defined
    at [eval]:1:1
    at Script.runInThisContext (vm.js:128:20)
    at Object.runInThisContext (vm.js:319:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at evalScript (internal/process/execution.js:94:25)
    at internal/main/eval_string.js:23:3
```

**Comment by nouremara** [comment]
hi, did you get an answer for that ? 
the docker is running but i cant see the map can you help me for that ?
